[project]
name = "evolution-text-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain-ollama>=0.2.1",
    "langchain>=0.3.10",
    "ollama>=0.4.4",
    "ruff>=0.8.2",
    "pandas>=2.2.3",
]
