extendedDiagMap = {
    "Dolor": "Dolor",
    "Patologia muscular": "Patología muscular",
    "Tendinopatia": "Tendinopatía",
    "Artrosis": "Artrosis",
    "Lumbalgia": "Lumbalgia",
    "PMR": "Polimialgia Reumática",
    "HAVI": "Hiperuricemia Asintomática",
    "Espondiloartrosis": "Espondiloartrosis",
    "Gota": "Gota",
    "Gonartrosis": "Gonartrosis",
    "Artritis Psoriásica": "Artritis Psoriásica",
    "ACG": "Arteritis de Células Gigantes",
    "Trocanteritis": "Trocanteritis",
    "OP": "Osteoporosis",
    "VASCULITIS": "Vasculitis",
    "Raynaud": "Fenómeno de Raynaud",
    "Dedo en resorte": "Dedo en resorte",
    "Artritis indiferenciada": "Artritis indiferenciada",
    "Hiperparatiroidismo": "Hiperparatiroidismo",
    "Omalgia": "Omalgia",
    "Condropatia rotuliana": "Condropatía rotuliana",
    "Osteoporosis": "Osteoporosis",
    "Dupuytren": "Enfermedad de Dupuytren",
    "Epicondilitis": "Epicondilitis",
    "ESCLEROSIS SISTÉMICA": "Esclerosis Sistémica",
    "Dorsalgia": "Dorsalgia",
    "Fascitis": "Fascitis",
    "LES": "Lupus Eritematoso Sistémico",
    "Artritis reumatoide": "Artritis Reumatoide",
    "AIJ": "Artritis Idiopática Juvenil",
    "Espondilitis anquilosante": "Espondilitis Anquilosante",
    "EDPP": "Espondilopatía Degenerativa Primaria",
    "Gonalgia": "Gonalgia",
    "Artralgias": "Artralgias",
    "Osteopenia": "Osteopenia",
    "Ciatica": "Ciática",
    "Mialgias": "Mialgias",
    "Sindrome Sjögren": "Síndrome de Sjögren",
    "Artralgias mecanicas": "Artralgias mecánicas",
    "Fibromialgia": "Fibromialgia",
    "ENF. INDIFERENCIADA DEL TEJIDO CONECTIVO": "Enfermedad Indiferenciada del Tejido Conectivo",
    "Deficit Vitamina D": "Déficit de Vitamina D",
    "Coxalgia": "Coxalgia",
    "Aplastamiento vertebral": "Aplastamiento vertebral",
    "STC": "Síndrome del Túnel Carpiano",
    "Coxopatia": "Coxopatía",
    "Esclerodermia": "Esclerodermia",
    "Artritis": "Artritis",
    "Escoliosis": "Escoliosis",
    "Discopatia": "Discopatía",
    "Morton": "Neuroma de Morton",
    "Estenosis de canal": "Estenosis de canal",
    "Artrosis axial": "Artrosis axial",
    "Baker": "Quiste de Baker",
    "Contractura": "Contractura",
    "Miopatia inflamatoria idiop.": "Miopatía Inflamatoria Idiopática",
    "Paget": "Enfermedad de Paget",
    "Lumbartrosis": "Lumbartrosis",
    "SAPHO": "Síndrome SAPHO",
    "Bursitis": "Bursitis",
    "Behcet": "Enfermedad de Behçet",
    "S. Autoinflamatorio": "Síndrome Autoinflamatorio",
    "Cervicobraquialgia": "Cervicobraquialgia",
    "Meniscopatia": "Meniscopatía",
    "Tenosinovitis": "Tenosinovitis",
    "SAF": "Síndrome Antifosfolípido",
    "EMTC": "Enfermedad Mixta del Tejido Conectivo",
    "Sarcoidosis": "Sarcoidosis",
    "Uveitis": "Uveítis",
    "Artritis septica": "Artritis séptica",
    "Polimialgia": "Polimialgia",
    "Dermatomiositis": "Dermatomiositis",
    "EPID": "Enfermedad Pulmonar Intersticial Difusa",
    "Crioglobulinemia": "Crioglobulinemia",
    "EII": "Enfermedad Inflamatoria Intestinal",
    "Microcristalina": "Artritis Microcristalina",
    "Sind. de SJÖGREN": "Síndrome de Sjögren",
    "Condromalacea": "Condromalacia",
    "Autoinflamatorio": "Síndrome Autoinflamatorio",
    "FOP": "Fibrodisplasia Osificante Progresiva",
    "Miopatia inflamatoria": "Miopatía Inflamatoria",
    "Beçhet": "Enfermedad de Behçet",
}

def validateResult(processedDiag:str, correctDiag:str):
    diagE1 = processedDiag.lower()
    diagE2 = extendedDiagMap.get(correctDiag, correctDiag.lower())

    return (diagE1 == diagE2) or diagE1.find(diagE2) != -1 or diagE2.find(diagE1) != -1